"""Voeg cost kolom toe aan Activity model

Revision ID: 198ae8fe02ff
Revises: 413a363126a0
Create Date: 2025-06-20 19:29:09.049354

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '198ae8fe02ff'
down_revision = '413a363126a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cost', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.drop_column('cost')

    # ### end Alembic commands ###
