"""Organisator toegevoegd

Revision ID: dff753bc05d6
Revises: 0332259e81b0
Create Date: 2025-09-29 00:00:14.968117

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dff753bc05d6'
down_revision = '0332259e81b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.add_column(sa.Column('organizer_id', sa.Integer(), nullable=True))
        batch_op.create_unique_constraint(batch_op.f('uq_activity_google_event_id'), ['google_event_id'])
        batch_op.create_foreign_key(batch_op.f('fk_activity_organizer_id_user'), 'user', ['organizer_id'], ['id'])

    with op.batch_alter_table('invitation_code', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_invitation_code_code'), ['code'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_user_email'), ['email'])
        batch_op.create_unique_constraint(batch_op.f('uq_user_username'), ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_user_username'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_user_email'), type_='unique')

    with op.batch_alter_table('invitation_code', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_invitation_code_code'), type_='unique')

    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_activity_organizer_id_user'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('uq_activity_google_event_id'), type_='unique')
        batch_op.drop_column('organizer_id')

    # ### end Alembic commands ###
